services:
  ai:
    image: eatda-ai:latest
    container_name: eatda-ai
    ports:
      - "8085:8000"
    volumes:
      - /home/ubuntu/eatda/ai:/root/eatda
    networks:
      - backend  # 기존에 쓰던 외부 네트워크 재사용

networks:
  backend:
    external: true
    name: backend