services:
  prod-blue:
    image: eatda:prod-blue
    container_name: eatda-prod-blue
    ports:
      - "8081:8080"
    networks:
      - backend

  prod-green:
    image: eatda:prod-green
    container_name: eatda-prod-green
    ports:
      - "8082:8080"
    networks:
      - backend

networks:
  backend:
    external: true
    name: backend