services:
  test-blue:
    image: eatda:test-blue
    container_name: eatda-test-blue
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
    volumes:
      - /home/ubuntu/eatda/test:/root/eatda
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  test-green:
    image: eatda:test-green
    container_name: eatda-test-green
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=test
    volumes:
      - /home/ubuntu/eatda/test:/root/eatda
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  backend:
    external: true
    name: backend
