spring:
  datasource:
    url: jdbc:mysql://prod-host:3306/prod_db
    username: prod_user
    password: prod_password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

springdoc:
  swagger-ui:
    config-url: /prod/v3/api-docs/swagger-config
