spring:
  application:
    name: EatDa
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  data:
    redis:
      host: redis
      port: 6379

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

logging:
  level:
    root: INFO
    com.global: INFO
    com.domain: INFO
    org.springframework.batch: INFO
    org.springframework.jdbc: INFO
    # --- Hibernate SQL 관련 모두 OFF ---
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.orm.jdbc.extract: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: OFF
    org.hibernate.stat: OFF

management: # Spring-Actuator 설정
  endpoints:
    web:
      exposure:
        include: health, prometheus # Spring-Actuator에서 외부로 노출할 엔드포인트
  prometheus:
    metrics: # 시스템이나 애플리케이션의 동작 상태를 수치로 표현한 정보
      export:
        enabled: true   # prometheus 엔드포인트 활성화 여부 *default = true

filestorage: # 파일 저장소 설정
  base-dir: /root/eatda
  base-url: ""
  host-base-dir: /home/ubuntu/eatda
  video:
    max-size-mb: 32
    request-timeout-sec: 20
    allowed-mime:
      - video/mp4
      - video/quicktime
      - video/webm

jwt:
  secret-key: SnnjiquvcPa8IZXG7XyOr36wYRfYLbkAsB6AxbPcnivRyAot428rMAvEXmFKFDH3vAkBmfEmS12YxSrZdTIknQ==
  access-expiration: 86400000
  refresh-expiration: 86400000
