spring:
  datasource:
    url: jdbc:mysql://mysql:3306/eatda?useSSL=false&serverTimezone=Asia/Seoul
    username: eatda
    password: a609
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  aop:
    proxy-target-class: true

logging:
  level:
    root: WARN
    com.domain: INFO
    com.global: INFO
    # --- Hibernate SQL 관련 모두 OFF ---
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.orm.jdbc.extract: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: OFF
    org.hibernate.stat: OFF

filestorage: # 파일 저장소 설정
  base-dir: /root/eatda
  base-url: "https://i13a609.p.ssafy.io/eatda/test"

springdoc:
  swagger-ui:
    config-url: /test/v3/api-docs/swagger-config
    url: /test/v3/api-docs
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
