spring:
  datasource:
    url: jdbc:mysql://mysql:3306/eatda?useSSL=false&serverTimezone=Asia/Seoul
    username: eatda
    password: a609
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  aop:
    proxy-target-class: true

filestorage: # 파일 저장소 설정
  base-dir: /root/eatda
  host-base-dir: /home/ubuntu/eatda/test
  base-url: "https://i13a609.p.ssafy.io/eatda/test"

springdoc:
  swagger-ui:
    config-url: /test/v3/api-docs/swagger-config
    url: /test/v3/api-docs
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
