spring:
  datasource:
    url: jdbc:mysql://mysql:3306/eatda?useSSL=false&serverTimezone=Asia/Seoul
    username: eatda
    password: a609
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.domain..controller: INFO
    com.domain..service: INFO
    com.domain..repository: INFO
    org.hibernate.SQL: INFO

springdoc:
  swagger-ui:
    config-url: /test/v3/api-docs/swagger-config
    url: /test/v3/api-docs
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
