spring:
  application:
    name: EatDa

management: # Spring-Actuator 설정
  endpoints:
    web:
      exposure:
        include: health, prometheus # Spring-Actuator에서 외부로 노출할 엔드포인트
  prometheus:
    metrics: # 시스템이나 애플리케이션의 동작 상태를 수치로 표현한 정보
      export:
        enabled: true   # prometheus 엔드포인트 활성화 여부 *default = true

redis:
  host: localhost
  port: 6370
  password: test
  timeout: 2000

filestorage: # 파일 저장소 설정
  image-root: ${user.home}/eatda/data/images  # 이미지 파일 저장 루트 경로
  video-root: ${user.home}/eatda/data/videos  # 비디오 파일 저장 루트 경로
